#!/usr/bin/env python3
"""
kb_graph_sync.py — mechanical prep step for the knowledge-graph layer of
the "knowledge library" (docs/KNOWLEDGE_LIBRARY.md). Parses frontmatter
from every _kb_files() entry and produces two outputs:

1. docs/KNOWLEDGE_LIBRARY_INDEX.md -- a grep-able master index, one line
   per frontmatter'd entry.
2. tmp_/kb_graph_sync_output.json -- entities+relations ready for
   mcp__memory__create_entities/create_relations, with the monkeydust:
   namespace prefix already applied (see KNOWLEDGE_LIBRARY.md's own
   doc comment on why the prefix is mandatory, not optional -- mcp__memory
   is very likely a store shared across every project on this machine).

IMPORTANT LIMITATION, by design not oversight: this script CANNOT itself
write to mcp__memory -- that's an MCP tool reachable only from an agent's
own tool-calling loop (stdio JSON-RPC protocol), not a REST endpoint a
standalone Python process can hit. This script does the mechanical half
(parse frontmatter -> entities/relations JSON, deterministic, re-runnable)
and an agent does the second half (read the JSON this script just wrote,
call mcp__memory__delete_entities for the whole monkeydust:* namespace --
full rebuild, never incremental, see the module-level rationale below --
then mcp__memory__create_entities/create_relations from the JSON). The
"agent does step 2" instruction is printed at the end of a normal run.

Full-rebuild rationale (same axiom md_doctor.py already uses -- "code is
truth, docs are a hypothesis" -- here: "frontmatter is truth, the graph is
derived and disposable"): the graph is NEVER hand-edited and NEVER
incrementally patched. Every sync deletes the whole monkeydust:* namespace
and recreates it from the current frontmatter state. This is O(N) per run
(N ~= 141 files, trivial) and eliminates an entire bug class (graph
silently diverging from markdown) at that cost.

Usage:
  tools/kb_graph_sync.py            # write both outputs
  tools/kb_graph_sync.py --json      # also print the graph JSON to stdout
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from md_doctor import _kb_files, _read, _parse_frontmatter, REPO_ROOT  # noqa: E402

OUT_INDEX = REPO_ROOT / "docs" / "KNOWLEDGE_LIBRARY_INDEX.md"
OUT_GRAPH_JSON = REPO_ROOT / "tmp_" / "kb_graph_sync_output.json"
NAMESPACE = "monkeydust:doc:"


def _entity_name(rel_path: str) -> str:
    return f"{NAMESPACE}{rel_path}"


def collect_entries():
    """Returns list of (rel_path, frontmatter_dict) for every _kb_files()
    entry that has valid, non-empty frontmatter -- files without one (or
    with unparseable YAML, same as DOC-11's own skip/fail distinction) are
    silently excluded here, not flagged (that's DOC-11's job, run via
    md_doctor.py separately)."""
    entries = []
    for f in _kb_files():
        text = _read(f)
        if not text.startswith("---\n"):
            continue
        fm = _parse_frontmatter(text)
        if not fm:
            continue
        entries.append((str(f.relative_to(REPO_ROOT)), fm))
    return entries


def build_graph(entries):
    entities = []
    relations = []
    for rel_path, fm in entries:
        name = _entity_name(rel_path)
        observations = [
            f"status: {fm.get('status', '')}",
            f"date: {fm.get('date', '')}",
            f"updated: {fm.get('updated', '')}",
            f"repo: {fm.get('repo', '')}",
            f"tags: {','.join(fm.get('tags') or [])}",
            f"summary: {fm.get('summary', '')}",
        ]
        entities.append({
            "name": name,
            "entityType": fm.get("type", "reference"),
            "observations": observations,
        })
        related = fm.get("related") or []
        related = related if isinstance(related, list) else [related]
        for target in related:
            if isinstance(target, str):
                relations.append({"from": name, "to": _entity_name(target), "relationType": "relates to"})
        superseded_by = fm.get("superseded_by")
        if isinstance(superseded_by, str) and superseded_by:
            relations.append({"from": name, "to": _entity_name(superseded_by), "relationType": "is superseded by"})
    return entities, relations


def write_index(entries):
    OUT_INDEX.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Knowledge Library — master index",
        "",
        "> Generated by `tools/kb_graph_sync.py` -- do not hand-edit, re-run",
        "> the script instead. Grep-able: one line per frontmatter'd entry.",
        "> See docs/KNOWLEDGE_LIBRARY.md for the schema.",
        "",
    ]
    for rel_path, fm in sorted(entries, key=lambda e: e[0]):
        tags = ",".join(fm.get("tags") or [])
        summary = fm.get("summary", "")
        lines.append(f"- [{fm.get('id', rel_path)}] {fm.get('type','')}/{fm.get('status','')} — `{rel_path}` — {summary} ({tags})")
    OUT_INDEX.write_text("\n".join(lines) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true", help="also print graph JSON to stdout")
    args = ap.parse_args()

    entries = collect_entries()
    entities, relations = build_graph(entries)

    write_index(entries)
    OUT_GRAPH_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_GRAPH_JSON.write_text(json.dumps({"entities": entities, "relations": relations}, indent=2))

    print(f"{len(entries)} frontmatter'd entries found.")
    print(f"Index written: {OUT_INDEX.relative_to(REPO_ROOT)}")
    print(f"Graph JSON written: {OUT_GRAPH_JSON.relative_to(REPO_ROOT)} ({len(entities)} entities, {len(relations)} relations)")
    if entities:
        print(
            "\nNEXT STEP (agent, not this script -- see module doc comment):\n"
            f"  1. mcp__memory__delete_entities for every existing 'monkeydust:*' entity (full rebuild)\n"
            f"  2. mcp__memory__create_entities from {OUT_GRAPH_JSON.relative_to(REPO_ROOT)}'s \"entities\"\n"
            f"  3. mcp__memory__create_relations from the same file's \"relations\""
        )
    if args.json:
        print(json.dumps({"entities": entities, "relations": relations}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
