#!/usr/bin/env python3
"""
md_biome_import.py — Assign biomes to all 4096 Kenshi zones using biomemap.png.
Strategy:
  1. Sample biomemap.png at each known zone's center pixel → build color→biome anchor map.
  2. For every unknown zone, find the nearest anchor color (RGB Euclidean distance).
  3. Write game/data/biome_map.txt: one entry per zone grid cell (64×64).
"""
import re, math
from PIL import Image

KENSHI_LAND = '/run/media/rdga1/win/SteamLibrary/steamapps/common/Kenshi/data/newland/land'
TERRAIN_CFG = 'game/data/terrain_config.txt'
OUT_FILE    = 'game/data/biome_map.txt'

# ── Load biomemap ─────────────────────────────────────────────────────────────
img = Image.open(f'{KENSHI_LAND}/biomemap.png').convert('RGBA')

def sample(zx, zz):
    px = min(zx * 16 + 8, 1023)
    py = min(zz * 16 + 8, 1023)
    r, g, b, _ = img.getpixel((px, py))
    return (r, g, b)

# ── Parse known zones from terrain_config.txt ────────────────────────────────
anchors = {}   # (r,g,b) → biome_str
known   = {}   # (zx,zz) → biome_str

with open(TERRAIN_CFG) as f:
    cur = {}
    for line in f:
        line = line.strip()
        for key in ('name','biome','grid_x','grid_z'):
            m = re.match(rf'{key}\s*=\s*(.+)', line)
            if m:
                cur[key] = m.group(1).strip()
        if all(k in cur for k in ('biome','grid_x','grid_z')):
            zx, zz = int(cur['grid_x']), int(cur['grid_z'])
            biome = cur['biome']
            color = sample(zx, zz)
            anchors[color] = biome
            known[(zx, zz)] = biome
            cur = {}

print(f"Anchor colors built from {len(known)} known zones → {len(anchors)} unique colors")

# ── Nearest-color biome lookup ────────────────────────────────────────────────
def nearest_biome(color):
    if color in anchors:
        return anchors[color]
    best_d, best_b = float('inf'), 'desert'
    r, g, b = color
    for (ar, ag, ab), biome in anchors.items():
        d = (r-ar)**2 + (g-ag)**2 + (b-ab)**2
        if d < best_d:
            best_d, best_b = d, biome
    return best_b

# ── Write biome_map.txt ───────────────────────────────────────────────────────
counts = {}
with open(OUT_FILE, 'w') as f:
    f.write("# Kenshi zone biome map — generated by md_biome_import.py\n")
    f.write("# format: zx,zz=biome\n")
    for zz in range(64):
        for zx in range(64):
            if (zx, zz) in known:
                biome = known[(zx, zz)]
            else:
                color = sample(zx, zz)
                biome = nearest_biome(color)
            f.write(f"{zx},{zz}={biome}\n")
            counts[biome] = counts.get(biome, 0) + 1

print(f"Written {OUT_FILE}")
for b, n in sorted(counts.items(), key=lambda x: -x[1]):
    print(f"  {b:15s} {n:4d} zones")
