#!/usr/bin/env python3
"""
terrain_zone_sweep.py — batch zone/biome visual sweep for monkey_dust_editor.

Parses game/data/terrain_config.txt (all Kenshi zones with grid_x/grid_z/
biome), generates one --exec Lua scenario that visits EVERY zone in the
editor's World3D viewport (the only view that holds the whole 64x64 world
at once — the game's own SceneRender is a fixed 9x9 window around spawn,
see docs/TERRAIN_ZONE_SWEEP_PLAN.md), screenshotting each into
tools/qa/captures/<run_id>/frames/frame_NNNN.png (the naming convention
tools/qa/qa_regression.py already expects for --baseline/--compare).

Usage:
  python3 tools/qa/terrain_zone_sweep.py --run-id 20260804_batch1
  build/tools/monkey_dust_editor --exec tmp_/zone_sweep_20260804_batch1.lua \
      --fast --seed 42 --max-seconds 600
  python3 tools/qa/qa_regression.py --baseline 20260804_batch1
  # ... later, after a shading change ...
  python3 tools/qa/terrain_zone_sweep.py --run-id 20260804_batch2
  build/tools/monkey_dust_editor --exec tmp_/zone_sweep_20260804_batch2.lua \
      --fast --seed 42 --max-seconds 600
  python3 tools/qa/qa_regression.py --compare 20260804_batch2 --baseline-id 20260804_batch1
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO_ROOT / "game" / "data" / "terrain_config.txt"
CAPTURES_DIR = REPO_ROOT / "tools" / "qa" / "captures"


def parse_zones(path: Path) -> list[dict]:
    zones = []
    cur = None
    for line in path.read_text().splitlines():
        s = line.strip()
        m = re.match(r"^zone=(\S+)$", s)
        if m:
            if cur is not None:
                zones.append(cur)
            cur = {"id": m.group(1), "name": None, "biome": None,
                   "grid_x": None, "grid_z": None}
            continue
        if cur is None:
            continue
        for key in ("name", "biome", "grid_x", "grid_z"):
            m = re.match(rf"^{key}=(.+)$", s)
            if m:
                val = m.group(1)
                cur[key] = int(val) if key.startswith("grid_") else val
    if cur is not None:
        zones.append(cur)
    return [z for z in zones if z["grid_x"] is not None and z["grid_z"] is not None]


def gen_lua(zones: list[dict], run_id: str) -> str:
    lines = [
        "-- AUTO-GENERATED by tools/qa/terrain_zone_sweep.py -- do not hand-edit",
        f"-- run_id={run_id}  zones={len(zones)}",
        'md.editor_open_panel("3D World")',
        "local ready = md.wait_until(function()",
        '    local loaded, total = md.editor_terrain_op("chunks_loaded")',
        "    return loaded >= total",
        "end, 20000)",
        'md.assert_true(ready, "editor terrain ready before sweep")',
        "",
    ]
    for i, z in enumerate(zones):
        frame = f"tools/qa/captures/{run_id}/frames/frame_{i:04d}.png"
        lines.append(f'md.editor_select_zone({z["grid_x"]}, {z["grid_z"]})')
        lines.append("md.wait_ticks(20)")
        lines.append(f'md.editor_screenshot("{frame}")')
        lines.append(f'md.log("zone {i+1}/{len(zones)}: {z["id"]} ({z["biome"]})")')
        lines.append("md.wait_ticks(10)")
        lines.append("")
    lines.append('md.log("terrain_zone_sweep: done")')
    lines.append("md.quit(0)")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run-id", required=True, help="capture id (used as tools/qa/captures/<run_id>/)")
    ap.add_argument("--config", default=str(CONFIG_PATH), help="terrain_config.txt path")
    ap.add_argument("--out", default=None, help="output Lua script path (default: tmp_/zone_sweep_<run_id>.lua)")
    args = ap.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"[zone_sweep] ERROR: config not found: {config_path}", file=sys.stderr)
        return 1

    zones = parse_zones(config_path)
    if not zones:
        print("[zone_sweep] ERROR: no zones parsed", file=sys.stderr)
        return 1

    frames_dir = CAPTURES_DIR / args.run_id / "frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    meta = {
        "run_id": args.run_id,
        "zone_count": len(zones),
        "zones": [{"frame": f"frame_{i:04d}.png", **z} for i, z in enumerate(zones)],
    }
    (CAPTURES_DIR / args.run_id / "zones.json").write_text(json.dumps(meta, indent=2))

    lua = gen_lua(zones, args.run_id)
    out_path = Path(args.out) if args.out else (REPO_ROOT / "tmp_" / f"zone_sweep_{args.run_id}.lua")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(lua)

    print(f"[zone_sweep] {len(zones)} zones -> {out_path}")
    print(f"[zone_sweep] captures will land in tools/qa/captures/{args.run_id}/frames/")
    print(f"[zone_sweep] run: build/tools/monkey_dust_editor --exec {out_path.relative_to(REPO_ROOT)} "
          f"--fast --seed 42 --max-seconds {max(120, len(zones) * 3)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
